PARSED_INT = 0
PARSED_CALL = 1
PARSED_IDENT = 2
PARSED_CHAR = 3
PARSED_KEYWORD = 4
PARSED_CONSTANT = 5

TYPE_INT = 0
TYPE_NIL = 1
TYPE_CONS = 2
TYPE_CHAR = 3
TYPE_BOOL = 4
TYPE_FUNCTION = 5
TYPE_BUILTIN_FUNCTION = 6
TYPE_FIXPOINT = 7
TYPE_UNKNOWN = 8
TYPE_ERROR = 9
